#This content are based on https://github.com/docker-library/buildpack-deps, under trusty sub-directory

#FROM ubuntu:trusty

FROM ubuntu:14.04.3

#RUN apt-get update && apt-get install -y --no-install-recommends \
#		ca-certificates \
#		curl \
#		wget \
#	&& rm -rf /var/lib/apt/lists/*

RUN apt-get install -y --no-install-recommends \
                ca-certificates \
                curl \
                wget \
        && rm -rf /var/lib/apt/lists/*
