FROM ubuntu:14.04.3
MAINTAINER Tang Feixiong, <tangfx128@gmail.com>

#RUN apt-get update && apt-get install -y --no-install-recommends \
#		bzr \
#		git \
#		mercurial \
#		openssh-client \
#		subversion \
#	&& rm -rf /var/lib/apt/lists/*

RUN apt-get install -y --no-install-recommands git openssh-client
